# docker-compose.yml
version: "3.8"

services:
  crafty-proxy:
    build: .
    container_name: crafty-proxy
    ports:
      - "25565:25565"
      - "25566:25566"
      - "25567:25567"
      - "25568:25568"
      - "25569:25569"
      - "25570:25570"
      - "25571:25571"
      - "25572:25572"
      - "25573:25573"
      - "25574:25574"
      - "25575:25575"
    volumes:
      - ./config/config.yaml:/craftyproxy/config/config.yaml:ro

    restart: unless-stopped
